apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rover-api-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ateixivi14/rover-api-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: rover-api

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
