apiVersion: apps/v1
kind: Deployment
metadata:
  name: rover-api
spec:
  selector:
    matchLabels:
      app: rover-api
  replicas: 2
  template:
    metadata:
      labels:
        app: rover-api
    spec:
      containers:
        - name: rover-api
          image: ateixivi14/rover-api:latest
          ports:
            - containerPort: 8080
